{{- if and .Values.gitopsReposConfig.enabled (gt (len .Values.gitopsReposConfig.vaultStaticSecrets) 0) }}
{{- range .Values.gitopsReposConfig.vaultStaticSecrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Values.gitopsReposConfig.defaultNamespace }}
spec:
  vaultAuthRef: {{ .vaultAuthRef | quote }}
  mount: {{ .mount | quote }}
  path: {{ .path | quote }}
  type: {{ .type | default "kv-v2" | quote }}
  {{- with .refreshAfter }}
  refreshAfter: {{ . | quote }}
  {{- end }}
  destination:
    name: {{ .destination.name | quote }}
    {{- if hasKey .destination "create" }}
    create: {{ .destination.create }}
    {{- else }}
    create: true
    {{- end }}
    {{- with .destination.overwrite }}
    overwrite: {{ . }}
    {{- end }}
    {{- with .destination.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .destination.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .destination.type }}
    type: {{ . | quote }}
    {{- end }}
{{- end }}
{{- end }}
