{{- if .Values.tektonZtp.pipelineRun.example.enabled }}
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: {{ .Values.tektonZtp.pipelineRun.example.generateName | quote }}
  namespace: openshift-pipelines
spec:
  pipelineRef:
    name: {{ .Values.tektonZtp.pipeline.name }}
  taskRunTemplate:
    serviceAccountName: {{ .Values.tektonZtp.serviceAccount.name }}
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: cluster-name
      value: {{ .Values.tektonZtp.pipelineRun.example.clusterName | quote }}
    - name: gitops-repo-url
      value: {{ .Values.tektonZtp.pipelineRun.example.gitopsRepoUrl | quote }}
    - name: git-revision
      value: {{ .Values.tektonZtp.pipelineRun.example.gitRevision | quote }}
    - name: git-base-branch
      value: {{ .Values.tektonZtp.pipelineRun.example.gitBaseBranch | quote }}
    - name: github-repo-slug
      value: {{ .Values.tektonZtp.pipelineRun.example.githubRepoSlug | quote }}
    - name: ztp-chart-relative-path
      value: {{ .Values.tektonZtp.pipelineRun.example.ztpChartRelativePath | quote }}
    - name: manifest-output-dir
      value: {{ .Values.tektonZtp.pipelineRun.example.manifestOutputDir | quote }}
    - name: skip-ansible
      value: {{ .Values.tektonZtp.pipelineRun.example.skipAnsible | quote }}
    - name: ansible-tags
      value: {{ .Values.tektonZtp.pipelineRun.example.ansibleTags | quote }}
    - name: run-sdn-prechecks
      value: "false"
    - name: run-hardware-validation
      value: "true"
    - name: run-network-connectivity-test
      value: "true"
    - name: skip-manual-approval-gate
      value: "true"
    - name: run-post-deploy-validation
      value: "false"
    - name: run-kube-burner-tests
      value: "false"
    - name: pr-title-prefix-modify
      value: {{ .Values.tektonZtp.pipelineRun.example.prTitlePrefixModify | quote }}
  workspaces:
    - name: shared
      volumeClaimTemplate:
        metadata:
          name: ztp-shared-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
{{- end }}
