apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: summit-common-operator-install
policyDefaults:
  namespace: policies
  remediationAction: inform
  severity: medium
  hubTemplateOptions:
    serviceAccountName: policy-hub-template-lookup
  placement:
    labelSelector:
      matchLabels:
        common: "true"
policies:
  - name: ztp-demo-apps-namespace-secret
    disabled: false
    manifests:
      - path: ../../../../../source-crs/namespace.yaml
      - path: ../../../../../source-crs/secret.yaml
