{{- if .Values.vaultSecretsOperator.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.vaultSecretsOperator.subscription.name }}
  namespace: {{ .Values.vaultSecretsOperator.namespace }}
spec:
  channel: {{ .Values.vaultSecretsOperator.subscription.channel | quote }}
  installPlanApproval: {{ .Values.vaultSecretsOperator.subscription.installPlanApproval }}
  name: vault-secrets-operator
  source: {{ .Values.vaultSecretsOperator.subscription.source | quote }}
  sourceNamespace: {{ .Values.vaultSecretsOperator.subscription.sourceNamespace | quote }}
  {{- with .Values.vaultSecretsOperator.subscription.startingCSV }}
  startingCSV: {{ . | quote }}
  {{- end }}
{{- end }}
