{{- if .Values.tektonMirror }}
{{- $tm := .Values.tenantMirrorTriggers | default dict -}}
{{- $elsa := ($tm.serviceAccount | default dict).name | default "el-mirror-tenant" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $elsa }}
  namespace: openshift-pipelines
{{- end }}
