{{- if .Values.tenantMirrorTriggers.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tenantMirrorTriggers.serviceAccount.name }}
  namespace: openshift-pipelines
{{- end }}
