mce:
  namespace: multicluster-engine
  operatorGroup:
    name: default
  subscription:
    name: multicluster-engine
    channel: stable-2.5
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace

acm:
  namespace: open-cluster-management
  operatorGroup:
    name: default
  subscription:
    name: advanced-cluster-management
    channel: release-2.15
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace

multiClusterHub:
  enabled: true
  name: multiclusterhub
  spec:
    availabilityConfig: Basic
