apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: summit-policies
policyDefaults:
  namespace: policies
  remediationAction: inform
  severity: medium
  hubTemplateOptions:
    serviceAccountName: policy-hub-template-lookup
  placement:
    labelSelector:
      matchLabels:
        common: "true"
policies:
  - name: ztp-demo-apps-namespace-secret
    disabled: false
    manifests:
      - path: manifests/namespace.yaml
      - path: manifests/secret.yaml
  - name: policy-openshift-gitops-pipelines
    disabled: false
    remediationAction: enforce
    severity: high
    placement:
      labelSelector:
        matchLabels:
          common: "true"
          name: local-cluster
    manifests:
      - path: manifests/gitops-subscription.yaml
      - path: manifests/pipelines-subscription.yaml
  - name: policy-ztp-operator-pipelines-pin
    disabled: true
    remediationAction: enforce
    severity: high
    manifests:
      - path: manifests/operator-pin-object-templates-raw.yaml
