ztpCommon:
  enabled: true
  namespace: ztp-common

operators:
  openshift-gitops-operator:
    channel: stable
    startingCSV: openshift-gitops-operator.v1.15.0
    upgradeApproval: Manual
    approvedCSVs:
      - openshift-gitops-operator.v1.15.0
  kubernetes-nmstate-operator:
    channel: stable
    startingCSV: kubernetes-nmstate-operator.v4.17.0
    upgradeApproval: Manual
    approvedCSVs:
      - kubernetes-nmstate-operator.v4.17.0
  openshift-pipelines-operator:
    channel: stable
    startingCSV: openshift-pipelines-operator-rh.v1.19.0
    upgradeApproval: Manual
    approvedCSVs:
      - openshift-pipelines-operator-rh.v1.19.0

clusterValues:
  data:
    etcdBackupSchedule: "0 */12 * * *"

cluster:
  name: prod-east-us-1
  namespace: prod-east-us-1

pullSecretRef:
  name: pull-secret

clusterNetworking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
  machineNetwork:
    - cidr: 192.168.30.0/24

nodeGroups:
  masters:
    - master-0
  workers: []

clusterDefaults:
  nodeRole: master
  rootDeviceHints:
    deviceName: /dev/disk/by-id/scsi-0000
  nicMapping:
    logicalName: eno1
    redfishMemberMatch: Embedded

bmcAddressTemplate: "redfish-virtualmedia://192.168.30.11/redfish/v1/Systems/1"

vault:
  enabled: true
  mount: kv-v2
  vaultAuthRef: vault-secrets-operator/vault-auth
  bmcCredentialsVaultPathPattern: "vault-root/data/prod/east/prod-hub-east-1/bmc/%s"

assistedDeployment:
  pullSecret:
    vaultPath: vault-root/data/prod/east/prod-hub-east-1/assisted-deployment-pull-secret

templateRefs:
  - name: example-sno-template
    namespace: openshift-siteconfig

extraManifestsRefs: []

extraLabels:
  ManagedCluster:
    common: "true"
    ztp-demo: "true"

extraAnnotations: {}
