{{- if and .Values.vault.enabled (ne (.Values.assistedDeployment.pullSecret.vaultPath | default "") "") }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ printf "%s-assisted-pull-secret" .Values.cluster.name | quote }}
  namespace: {{ .Values.cluster.namespace | quote }}
spec:
  vaultAuthRef: {{ .Values.vault.vaultAuthRef | quote }}
  mount: {{ .Values.vault.mount | quote }}
  path: {{ .Values.assistedDeployment.pullSecret.vaultPath | quote }}
  type: kv-v2
  destination:
    name: {{ .Values.pullSecretRef.name | quote }}
    create: true
    {{- with .Values.assistedDeployment.pullSecret.destinationOverwrite }}
    overwrite: {{ . }}
    {{- end }}
{{- end }}
