# oc mirror + git promote helpers for OpenShift Pipelines (build and set tektonMirror.pipeline.mirrorImage).
# Build: podman build --build-arg OCP_CLIENT_VERSION=4.16.3 -t your-registry/oc-mirror-runner:latest .

FROM registry.redhat.io/openshift4/ose-tools-rhel9:v4.16

ARG OCP_CLIENT_VERSION=4.16.3
ARG TARGETARCH=amd64

USER 0

RUN microdnf install -y jq git && microdnf clean all

RUN curl -sL "https://mirror.openshift.com/pub/openshift-v4/${TARGETARCH}/clients/ocp/${OCP_CLIENT_VERSION}/oc-mirror.tar.gz" \
    | tar xz -C /usr/local/bin \
    && chmod +x /usr/local/bin/oc-mirror

RUN curl -sL "https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64" -o /usr/local/bin/yq \
    && chmod +x /usr/local/bin/yq

RUN curl -sL "https://github.com/cli/cli/releases/download/v2.49.0/gh_2.49.0_linux_amd64.tar.gz" | tar xz -C /tmp \
    && mv "/tmp/gh_2.49.0_linux_amd64/bin/gh" /usr/local/bin/gh \
    && chmod +x /usr/local/bin/gh

# Non-root compatible with OpenShift Pipelines
RUN mkdir -p /home/default && chown -R 1001:0 /home/default && chmod -R g=u /home/default
USER 1001
WORKDIR /home/default
ENV HOME=/home/default

CMD ["/usr/local/bin/oc-mirror", "version"]
