# UBI-based image with oc and oc-mirror for OpenShift Pipelines (OCP Pipelines) mirror pipelines.
# Build with: podman build --build-arg OCP_CLIENT_VERSION=4.16.3 -t your-registry/oc-mirror-runner:latest .

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

ARG OCP_CLIENT_VERSION=4.16.3
ARG TARGETARCH=amd64

USER 0

RUN microdnf install -y curl tar gzip ca-certificates shadow-utils skopeo \
    && microdnf clean all

# openshift-client (oc, kubectl)
RUN curl -sL "https://mirror.openshift.com/pub/openshift-v4/${TARGETARCH}/clients/ocp/${OCP_CLIENT_VERSION}/openshift-client-linux.tar.gz" \
    | tar xz -C /usr/local/bin oc kubectl \
    && chmod +x /usr/local/bin/oc /usr/local/bin/kubectl

# oc-mirror (same release stream as client; adjust version if mirror lacks asset)
RUN curl -sL "https://mirror.openshift.com/pub/openshift-v4/${TARGETARCH}/clients/ocp/${OCP_CLIENT_VERSION}/oc-mirror.tar.gz" \
    | tar xz -C /usr/local/bin \
    && chmod +x /usr/local/bin/oc-mirror

# Non-root runtime (OpenShift Pipelines can still override user)
RUN useradd -u 1001 -r -g 0 -m -s /sbin/nologin default
WORKDIR /home/default
RUN chown -R 1001:0 /home/default && chmod -R g=u /home/default
USER 1001

ENV HOME=/home/default

CMD ["/usr/local/bin/oc-mirror", "version"]
