{{- if .Values.tektonBulkZtp.pipelineRun.example.enabled }}
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: {{ .Values.tektonBulkZtp.pipelineRun.example.generateName | quote }}
  namespace: openshift-pipelines
spec:
  pipelineRef:
    name: {{ .Values.tektonBulkZtp.pipeline.name }}
  taskRunTemplate:
    serviceAccountName: {{ .Values.tektonBulkZtp.serviceAccount.name }}
  params:
    - name: max-concurrent
      value: {{ .Values.tektonBulkZtp.bulk.maxConcurrent | toString | quote }}
    - name: exclude-managed-clusters
      value: {{ .Values.tektonBulkZtp.bulk.excludeManagedClusters | quote }}
    - name: managed-cluster-label-selector
      value: {{ .Values.tektonBulkZtp.bulk.managedClusterLabelSelector | quote }}
    - name: child-gitops-repo-url
      value: {{ .Values.tektonBulkZtp.childDefaults.gitopsRepoUrl | quote }}
    - name: child-github-repo-slug
      value: {{ .Values.tektonBulkZtp.childDefaults.githubRepoSlug | quote }}
{{- end }}
