# Deploys ACM Policies that install OpenShift Pipelines and OpenShift GitOps operators on the hub.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-ocp-operators-policy
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/aprincipRedhat/rh-summit-gitops-tmobile.git
    targetRevision: main
    path: hub/day2/helm/ocp-operators-policy
    helm:
      releaseName: ocp-operators-policy
      valueFiles:
        - values.yaml
        - ../../../hub-values/dev/east/hub-values/dev-hub-east-1.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: local-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true