# Deploys the bulk ZTP OCP Pipelines Helm chart to openshift-pipelines.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-tekton-bulk-ztp
  namespace: openshift-gitops
  labels:
    summit.redhat.com/day2: "true"
    summit.redhat.com/component: tekton-bulk-ztp
spec:
  project: default
  source:
    repoURL: https://github.com/aprincipRedhat/rh-summit-gitops-tmobile.git
    targetRevision: main
    path: hub/day2/helm/bulk-ztp-pipeline
    helm:
      releaseName: tekton-bulk-ztp-pipeline
      valueFiles:
        - ../../../hub-values/dev/east/hub-values/dev-hub-east-1.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
