{{- $bulkSA := (.Values.tektonBulkZtp | default dict).serviceAccount | default dict -}}
{{- $san := $bulkSA.name | default "pipeline-bulk-ztp-gitops" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-tekton" $san }}
  namespace: openshift-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-tekton" $san }}
subjects:
  - kind: ServiceAccount
    name: {{ $san }}
    namespace: openshift-pipelines
