{{- $sa := (.Values.tektonBulkZtp | default dict).serviceAccount | default dict -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name | default "pipeline-bulk-ztp-gitops" }}
  namespace: openshift-pipelines
