{{- if .Values.ztpCommon.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.ztpCommon.namespace | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-unique-config" .Values.cluster.name | quote }}
  namespace: {{ .Values.ztpCommon.namespace | quote }}
data:
  clusterName: {{ .Values.cluster.name | quote }}
{{- $cv := .Values.clusterValues | default dict }}
{{- range $k, $v := ($cv.data | default dict) }}
  {{ $k }}: |-
{{ $v | toString | trim | nindent 4 }}
{{- end }}
{{- end }}
