apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ansible.preflightConfigMapName | quote }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: ztp-ansible-preflight
    app.kubernetes.io/component: tekton-ztp-pipeline
data:
{{- range $path, $content := .Files.Glob "files/ansible/**" }}
{{- if hasSuffix ".yml" $path }}
{{- $rel := trimPrefix "files/ansible/" $path }}
  {{ $rel | replace "/" "__" }}: |
{{ $content | toString | nindent 4 }}
{{- end }}
{{- end }}
