apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-role" .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ .Values.github.secretName | quote }}]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [{{ .Values.ansible.preflightConfigMapName | quote }}]
    verbs: ["get"]
