apiVersion: v2
name: tekton-mirror
description: OpenShift Pipelines (OCP Pipelines) Pipeline to run oc mirror using ImageSetConfiguration from a ConfigMap
type: application
version: 0.1.0
appVersion: "0.1.0"
