{{- if .Values.vaultHubCredentialSync.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-acm-hub-vault-credential-sync
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: {{ include "managed-apps.repoURL" . | quote }}
    targetRevision: {{ include "managed-apps.targetRevision" . | quote }}
    path: hub-clusters/day2/applications/acm-hub-vault-credential-sync
    helm:
      releaseName: acm-hub-vault-credential-sync
      valueFiles:
        - {{ include "managed-apps.hubValuesFromDay2App" . | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
{{- end }}
