apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-policy-generator-gitops-patch
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: {{ include "managed-apps.repoURL" . | quote }}
    targetRevision: {{ include "managed-apps.targetRevision" . | quote }}
    path: hub-clusters/day2/applications/policy-generator-gitops-patch
    helm:
      releaseName: policy-generator-gitops-patch
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
