{{- if .Values.vaultHubConfiguration.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-vault-hub-configuration
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: {{ include "managed-apps.repoURL" . | quote }}
    targetRevision: {{ include "managed-apps.targetRevision" . | quote }}
    path: hub-clusters/day2/applications/vault-hub-configuration
    helm:
      releaseName: vault-hub-configuration
      valueFiles:
        - {{ include "managed-apps.hubValuesFromDay2App" . | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
{{- end }}
