{{- if .Values.tenantMirrorTriggers.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-tekton-mirror-tenant-triggers
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: {{ include "managed-apps.repoURL" . | quote }}
    targetRevision: {{ include "managed-apps.targetRevision" . | quote }}
    path: cluster-automation/spoke-automation/mirror-tenant-triggers
    helm:
      releaseName: tekton-mirror-tenant-triggers
      valueFiles:
        - {{ include "managed-apps.hubValuesFromClusterAutomation" . | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-pipelines
  ignoreDifferences:
    - group: triggers.tekton.dev
      kind: EventListener
      jsonPointers:
        - /spec/resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
{{- end }}
