namespace: openshift-pipelines
createNamespace: false

serviceAccount:
  name: pipeline-ztp-gitops

github:
  secretName: github-tekton-token
  secretKey: token

ansible:
  preflightConfigMapName: ztp-ansible-preflight

images:
  git: docker.io/alpine/git:v2.43.0
  ansible: quay.io/ansible/ansible-runner:latest
  helm: docker.io/alpine/helm:3.14.4
  alpineTools: docker.io/alpine:3.19

pipeline:
  name: ztp-cluster-render-pr

pipelineRun:
  example:
    enabled: false
    generateName: ztp-cluster-demo-
    clusterName: dev-east-us-1
    gitopsRepoUrl: https://github.com/aprincipRedhat/rh-summit-gitops-tmobile.git
    gitRevision: main
    gitBaseBranch: main
    githubRepoSlug: aprincipRedhat/rh-summit-gitops-tmobile
    ztpChartRelativePath: spokes/cluster-automation/helm/ztp-spoke
    manifestOutputDir: spokes/clusters
    skipAnsible: "true"
    ansibleTags: dns
    prTitlePrefixModify: "Update cluster"
