{{- if and .Values.vaultHubConfiguration.enabled .Values.vaultHubConfiguration.vaultAuth.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vaultHubConfiguration.vaultAuth.kubernetes.serviceAccount | quote }}
  namespace: {{ .Values.vaultHubConfiguration.operatorNamespace | quote }}
{{- end }}
