{{- if and .Values.vaultHubConfiguration.enabled .Values.vaultHubConfiguration.vaultAuth.enabled }}
{{- if .Values.vaultHubConfiguration.vaultAuthGlobal.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Values.vaultHubConfiguration.vaultAuth.name | quote }}
  namespace: {{ .Values.vaultHubConfiguration.operatorNamespace | quote }}
spec:
  vaultAuthGlobalRef:
    name: {{ .Values.vaultHubConfiguration.vaultAuthGlobal.name | quote }}
    namespace: {{ .Values.vaultHubConfiguration.operatorNamespace | quote }}
  {{- with .Values.vaultHubConfiguration.vaultAuth.allowedNamespaces }}
  allowedNamespaces:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  method: appRole
  {{- with .Values.vaultHubConfiguration.vaultAuth.mount }}
  mount: {{ . | quote }}
  {{- end }}
  appRole:
    secretRef: {{ .Values.vaultHubConfiguration.vaultAuth.appRole.secretRef | quote }}
{{- else }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Values.vaultHubConfiguration.vaultAuth.name | quote }}
  namespace: {{ .Values.vaultHubConfiguration.operatorNamespace | quote }}
spec:
  vaultConnectionRef: {{ .Values.vaultHubConfiguration.vaultAuth.vaultConnectionRef | quote }}
  method: kubernetes
  mount: {{ .Values.vaultHubConfiguration.vaultAuth.kubernetes.mount | default "kubernetes" | quote }}
  {{- with .Values.vaultHubConfiguration.vaultAuth.allowedNamespaces }}
  allowedNamespaces:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  kubernetes:
    role: {{ .Values.vaultHubConfiguration.vaultAuth.kubernetes.role | quote }}
    serviceAccount: {{ .Values.vaultHubConfiguration.vaultAuth.kubernetes.serviceAccount | quote }}
    tokenExpirationSeconds: {{ .Values.vaultHubConfiguration.vaultAuth.kubernetes.tokenExpirationSeconds | default 600 }}
    {{- with .Values.vaultHubConfiguration.vaultAuth.kubernetes.audiences }}
    audiences:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
