apiVersion: v1
kind: Secret
metadata:
  name: ztp-demo-app-credentials
  namespace: ztp-demo-apps
  labels:
    app.kubernetes.io/part-of: summit-policies
type: Opaque
stringData:
  username: "REPLACE_ME"
  password: "REPLACE_ME"
