{{- if dig "ztpReleaseServer" "enabled" false (fromJson (toJson .Values)) }}
{{- $ns := dig "ztpReleaseServer" "namespace" "ztp-release-server" (fromJson (toJson .Values)) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ztp-release-server
  namespace: {{ $ns }}
  labels:
    app: ztp-release-server
spec:
  to:
    kind: Service
    name: ztp-release-server
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
