{{- if .Values.tektonMirror.pipelineRun.example.enabled }}
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: {{ .Values.tektonMirror.pipelineRun.example.generateName | quote }}
  namespace: openshift-pipelines
spec:
  pipelineRef:
    name: {{ .Values.tektonMirror.pipeline.name }}
  taskRunTemplate:
    serviceAccountName: {{ .Values.tektonMirror.serviceAccount.name }}
  params:
    - name: dest-registry
      value: {{ .Values.tektonMirror.pipelineRun.example.destRegistry | quote }}
    - name: extra-flags
      value: {{ .Values.tektonMirror.pipelineRun.example.extraFlags | quote }}
  workspaces:
    - name: imageset
      configMap:
        name: {{ .Values.tektonMirror.rbac.configMapName }}
    - name: registry-auth
      secret:
        secretName: {{ .Values.tektonMirror.rbac.secretName }}
{{- end }}
